## Load module and libraries

In [1]:
from selenium import webdriver
from datetime import datetime, timedelta
from random import randrange
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import requests
import calendar
import json
import time
import os

## Download login info as cookie (run this only when you need cookie)

In [218]:
# ## Open the virtual browser 
# driver = webdriver.Firefox()

# ## Open the website 
# website = 'https://enlighten.enphaseenergy.com/systems/1302574/inverters/28563594/time_series_x?&date=2019-05-04&stat=POWR%2CDCV%2CDCA%2CACV%2CACHZ%2CTMPI'
# driver.get(website)

# ## Username and password
# user="mfeng@umass.edu"
# password="UmassCS!"

# ## Login the website
# driver.find_element_by_id('user_email').click()
# driver.find_element_by_id("user_email").send_keys(user)
# driver.find_element_by_id('user_password').click()
# driver.find_element_by_id("user_password").send_keys(password)
# driver.find_element_by_id('submit').click()

# ## Store the login info in cookie
# driver.get(website)
# cookie_items = driver.get_cookies()

# post = {}

# for cookie_item in cookie_items:
#     post[cookie_item['name']] = cookie_item['value']
    
# cookie_str = json.dumps(post)
# with open('cookie.txt', 'w', encoding='utf-8') as f:
#     f.write(cookie_str)
# f.close

## Download data for each panel

In [3]:
# Use the stored cookie to login and keep session open
with open('cookie.txt', 'r',encoding='utf-8') as f:
    cookie = f.read()
cookies = json.loads(cookie)

In [4]:
## Align microinverter's serial number with inverter ID
system_id = '1302574'

## Inverter serial number and ID is aligned one by one 
inverter_sn = ['121721038143', '121721037801', '121721037691', '121721038936', '121721038148', 
             '121721037892', '121721037821', '121721037806', '121721038079', '121721038122', 
             '121721038133', '121721037662', '121721037689', '121721037871', '121721037817', 
             '121721038020', '121721038147', '121721038076', '121721038911', '121721037842', 
             '121721037788', '121721037686', '121721037867', '121721038108', '121721038125', 
             '121721037685', '121721038107', '121721038154', '121721038144', '121721037880', 
             '121721038037']

inverter_id = [str(28563593+i) for i in range(len(inverter_sn))]
inverter_sn_id = {k:v for k,v in zip(inverter_id,inverter_sn)}

In [5]:
print("Microinverter ID: serial number")
inverter_sn_id

Microinverter ID: serial number

{'28563593': '121721038143',
 '28563594': '121721037801',
 '28563595': '121721037691',
 '28563596': '121721038936',
 '28563597': '121721038148',
 '28563598': '121721037892',
 '28563599': '121721037821',
 '28563600': '121721037806',
 '28563601': '121721038079',
 '28563602': '121721038122',
 '28563603': '121721038133',
 '28563604': '121721037662',
 '28563605': '121721037689',
 '28563606': '121721037871',
 '28563607': '121721037817',
 '28563608': '121721038020',
 '28563609': '121721038147',
 '28563610': '121721038076',
 '28563611': '121721038911',
 '28563612': '121721037842',
 '28563613': '121721037788',
 '28563614': '121721037686',
 '28563615': '121721037867',
 '28563616': '121721038108',
 '28563617': '121721038125',
 '28563618': '121721037685',
 '28563619': '121721038107',
 '28563620': '121721038154',
 '28563621': '121721038144',
 '28563622': '121721037880',
 '28563623': '121721038037'}

In [6]:
## Group panels based on their facing direction (west/east/lower)
west_roof = ['121721038107', '121721037685', '121721038037', '121721038147', '121721037806', 
             '121721037892', '121721038143']
east_roof = ['121721037871', '121721037662', '121721037801', '121721037691', '121721037880',
             '121721038936', '121721038122', '121721038148', '121721038133']
lower_roof = ['121721037686', '121721037788', '121721038076', '121721038079', '121721037867', 
              '121721038020', '121721037817', '121721038144', '121721038911', '121721037842']

west_roof_id = []
east_roof_id = []
lower_roof_id = []

for inverter in inverter_sn:
    if inverter in west_roof:
        west_roof_id.append(inverter_id[inverter_sn.index(inverter)])
    elif inverter in east_roof:
        east_roof_id.append(inverter_id[inverter_sn.index(inverter)])
    elif inverter in lower_roof:
        lower_roof_id.append(inverter_id[inverter_sn.index(inverter)])

In [7]:
## Generate calendar list by defining start and end date

start_day = '2017-9-11'
end_day = '2018-3-12'
start_day = datetime.strptime(start_day, '%Y-%m-%d')
end_day = datetime.strptime(end_day, '%Y-%m-%d')
total_day = abs((end_day - start_day).days)


def calendar_test(day, count, date_list = None):
    if date_list is None:
        date_list = []
    if count == 0:
        return date_list
    count -= 1
    day = day + timedelta(days=1)
    date = day.isoformat().split('T')[0]
    date_list.append(date)
    
    calendar_test(day,count,date_list)
    
    return date_list

day_list = calendar_test(start_day,total_day)

In [8]:
## Formula: website = link_1 + system_id + link_2 + inverter_id + link_3 + date + link_4
link_1 = 'https://enlighten.enphaseenergy.com/systems/'
link_2 = '/inverters/'
link_3 = '/time_series_x?&date='
link_4 = '&stat=POWR%2CDCV%2CDCA%2CACV%2CACHZ%2CTMPI'

In [9]:
# Define which direction of roof panels you'd like to collect from
roof_panel = lower_roof_id

In [134]:
for inverter_id in roof_panel:
    print('Inverter ID: {}'.format(inverter_id))
    
    info = {'date_time':[], 'power':[], 'power_unknown':[], 'DCV':[], 
            'DCA':[], 'ACV':[], 'ACHZ':[], 'TMPI':[]}
    for day in day_list:
        # website address where data is stored
        website = link_1 + system_id + link_2 + inverter_id + link_3 + day + link_4
        # access data in json format from the website
        res = requests.get(url=website, cookies=cookies)
        data = res.json()
        
        # extract time information 
        for ii in data['POWR']:
            date_time = time.struct_time(time.localtime(ii[0]))
            date = 10000*date_time[0]+100*date_time[1]+1*date_time[2]
            time_ = 100*date_time[3]+1*date_time[4]
            date_time = date*10000+time_
            
            info['date_time'].append(date_time)
            info['power'].append(ii[1])
            info['power_unknown'].append(ii[2])
                        
        for ii in data['DCV']:
            info['DCV'].append(ii[1])
            
        for ii in data['DCA']:
            info['DCA'].append(ii[1])
            
        for ii in data['ACV']:
            info['ACV'].append(ii[1])
            
        for ii in data['ACHZ']:
            info['ACHZ'].append(ii[1])
            
        for ii in data['TMPI']:
            info['TMPI'].append(ii[1])
            
    # Save downloaded data for each panel
    data = pd.DataFrame(dict([(k,pd.Series(v)) for k,v in info.items() ]))
    export_csv = data.to_csv (str(inverter_id)+".csv", index = True, header=True)

Inverter ID: 28563601
Inverter ID: 28563607
Inverter ID: 28563608
Inverter ID: 28563610
Inverter ID: 28563611
Inverter ID: 28563612
Inverter ID: 28563613
Inverter ID: 28563614
Inverter ID: 28563615
Inverter ID: 28563621

## Clean Data

In [25]:
# Load files from current directory
files = os.listdir(os.getcwd())
files = [file for file in files if file[:-4] in roof_panel]

In [26]:
def load_data(file):
    
    ## Load dataset 
    dataset = pd.read_csv(file, index_col=0)
    dataset = dataset.set_index('date_time')
    dataset = dataset.drop(['power_unknown', 'DCV', 'DCA', 'ACV', 'ACHZ', 'TMPI'], axis=1)
    dataset = dataset.rename(columns = {'power': str(file[:-4])})
    
    return dataset

In [27]:
dataset = [load_data(file) for file in files]

In [28]:
# Merge power output for each panel based on timestamp
data = dataset[0]
for i in range(1, len(dataset)):
#     data = pd.merge(data, dataset[i], left_index=True, right_index=True)
    data = data.join(dataset[i], lsuffix='_caller', rsuffix='_other')
    data = data.interpolate(method ='linear', limit_direction ='both', limit = 3) 

# Remove duplicated row   
data = data.reset_index().drop_duplicates(subset='date_time',keep='first').set_index('date_time')
data = data.dropna()

In [29]:
data

,28563608,28563621,28563607,28563613,28563612,28563610,28563611,28563615,28563601,28563614
date_time,,,,,,,,,,
201709120646,1.145,2.255,2.061000,0.6700,1.749000,0.886,1.256,2.296000,1.3230,0.961
201709120648,2.072,2.255,2.061000,0.6700,2.236000,0.886,2.287,2.296000,1.3230,0.974
201709120649,2.313,2.255,2.061000,2.3850,2.485000,0.925,2.554,2.398000,1.3230,1.015
201709120650,2.551,2.483,2.633000,2.6540,2.725000,0.962,2.765,2.500000,2.6150,1.020
201709120651,2.800,2.750,2.804000,2.8490,2.925000,0.962,3.000,2.943000,2.8550,1.019
...,...,...,...,...,...,...,...,...,...,...
201803071231,0.304,0.831,0.365758,1.0410,0.000915,0.000,1.013,0.001009,2.7160,0.247
201803071233,0.295,0.831,0.387273,1.0250,0.000988,0.468,1.000,0.001209,2.7580,0.259
201803071234,0.349,0.831,0.408788,1.1310,0.001062,0.674,1.035,0.001405,2.8000,0.373
201803071235,0.342,0.831,0.430303,0.9865,0.001136,0.597,1.027,0.001600,2.8660,0.260
201803071237,0.136,0.831,0.451818,0.8420,0.001208,0.000,0.926,0.001796,2.6505,0.147

In [30]:
# Save the cleaned data
export_csv = data.to_csv ("cleaned_data.csv", index = True, header=True)